services:
  database:
    build:
      context: ./src/database
      dockerfile: Dockerfile
    container_name: enpal-coding-challenge-db
    ports:
      - "5432:5432"
    restart: always
  yf.enpalchallange.api:
    image: yf.enpalchallange.api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development